name: CI - build, test, deploy reports

on:                                
  push:
    branches: [ master ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:      	   
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    
    - name: Report
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_REPORTS_SECRET }}
    - name: Build and Test
      run: |
           ./gradlew build |
           ./gradlew test
    - name: deployReports
      run: ./gradlew deployReports
    - name: prep spotbugs
      run: ./gradlew --stop
